version: 1
groups:
  - annotation: ckanext-idb-theme
    options:
      - key: theme.idb.collapsed_facets
        type: list
        default:
          - res_format
          - license
        description: |
          List of facet fields to be collapsed by default on the search results page.

      - key: theme.idb.hide_empty_followers
        type: bool
        default: true
        description: |
          Hide follower counters in sidebar summaries when the count is zero.

      - key: theme.idb.home_title
        default: ""
        description: |
          Browser title for the portal homepage.

      - key: theme.idb.hide_user_image_upload
        type: bool
        default: false
        description: |
          Hide user image upload controls from the user edit form.
